name: ElytraMix
version: ${project.version}
authors: [7isenko, hevav, urFate] # Fork of ScenarioMix by 7isenko
website: https://elytrium.net
api-version: 1.15 # 1.16 breaks compatibility with 1.15; 1.15 allows to get 1.16 items in Material.values()
main: net.elytrium.elytramix.Plugin
depend:
  - WorldGuard

commands:
  es:
    description: Открывает меню сценариев ElytraMix
    usage: /es или /es <сценарий> <конфиг> <значение>
    permission: elytramix.menu
    aliases: [mix]
  ec:
    description: Открывает меню быстрых команд ElytraMix
    usage: /ec
    permission: elytramix.cmd

permissions:

  # Main permissions

  elytramix.menu:
    default: op
    description: Открывать меню сценариев
  elytramix.cmd:
    default: op
    description: Открывать меню быстрых команд
  elytramix.tools:
    default: op
    description: Использовать инструменты с плагина
  elytramix.default:
    default: true
    description: Позволяет использовать стандартные команды
  elytramix.debug:
    default: op
    description: Показывать сообщения отладки