name: ElytraMix
version: ${project.version}
authors: [7isenko, hevav, urFate] # Fork of ScenarioMix by 7isenko
website: https://elytrium.net
api-version: 1.15 # 1.16 breaks compatibility with 1.15; 1.15 allows to get 1.16 items in Material.values()
main: net.elytrium.elytramix.Plugin
depend:
  - WorldGuard

commands:
  es:
    description: Открывает меню сценариев ElytraMix
    usage: /es или /es <сценарий> <конфиг> <значение>
    permission: elytramix.menu
    aliases: [mix]
  ec:
    description: Открывает меню быстрых команд ElytraMix
    usage: /ec или /ec <быстрая команда>
    permission: elytramix.cmd
    aliases: [essentials]
  bc:
    description: Отправляет сообщение на весь сервер
    usage: /bc <сообщение>
    permission: elytramix.tools
    aliases: [broadcast]
  day:
    description: Устанавливает дневное время суток
    usage: /day
    permission: elytramix.tools
  fly:
    description: Включает режим полёта для игрока
    usage: /fly <игрок | *> <enable | disable>
    permission: elytramix.tools
  gm:
    description: Переключает игровой режим
    usage: /gm <режим> <игрок | *>
    permission: elytramix.tools
    aliases: [gamemode]
  heal:
    description: Исцеляет игрока
    usage: /heal <игрок | *>
    permission: elytramix.tools
  kickall:
    description: Кикает всех игроков
    usage: /kickall
    permission: elytramix.tools
  mobkill:
    description: Убивает всех мобов в заданом радиусе
    usage: /mobkill <радиус>
    permission: elytramix.tools
  night:
    description: Устанавливает ночное время суток
    usage: /night
    permission: elytramix.tools
  powertool:
    description: Делает из предмета волшебную палочку
    usage: /pt <команда>
    permission: elytramix.tools
    aliases: [pt]
  rain:
    description: Устанавливает дождливую погоду
    usage: /rain
    permission: elytramix.tools
  sun:
    description: Устанавливает солнечную погоду
    usage: /sun
    permission: elytramix.tools
  tpall:
    description: Телепортирует всех игроков к вам
    usage: /tpall
    permission: elytramix.tools
  tphere:
    description: Телепортирует игрока к вам
    usage: /s <Игрок>
    permission: elytramix.tools
    aliases: [s]
  speed:
    description: Изменяет скорость движения
    usage: /speed <число>
    permission: elytramix.tools
  spawn:
    description: Телепортирует игрока на спавн
    usage: /spawn
    permission: elytramix.default
  setspawn:
    description: Устанавливает спавн в мире где вы находитесь
    usage: /setspawn
    permission: elytramix.tools
  back:
    description: Возвращает вас в последнюю известную точку
    usage: /back
    permission: elytramix.tools


permissions:
  elytramix.menu:
    default: op
    description: Открывать меню сценариев
  elytramix.cmd:
    default: op
    description: Открывать меню быстрых команд
  elytramix.tools:
    default: op
    description: Использовать инструменты с плагина
  elytramix.default:
    default: true
    description: Позволяет использовать стандартные команды
  elytramix.debug:
    default: op
    description: Показывать сообщения отладки