name: ElytraMix
version: ${project.version}
authors: [7isenko, hevav, urFate] # Fork of ScenarioMix by 7isenko
website: https://elytrium.net
api-version: 1.15 # 1.16 breaks compatibility with 1.15; 1.15 allows to get 1.16 items in Material.values()
main: net.elytrium.elytramix.Plugin
depend:
  - WorldGuard

commands:
  es:
    description: Открывает меню сценариев ElytraMix
    usage: /es или /es <сценарий> <конфиг> <значение>
    permission: elytramix.menu
    aliases: [mix]
  ec:
    description: Открывает меню быстрых команд ElytraMix
    usage: /ec или /ec <быстрая команда>
    permission: elytramix.cmd
    aliases: [essentials]
  bc:
    description: Отправляет сообщение на весь сервер
    usage: /bc <сообщение>
    permission: elytramix.essentials.broadcast
    aliases: [broadcast]
  day:
    description: Устанавливает дневное время суток
    usage: /day
    permission: elytramix.essentials.time
  fly:
    description: Включает режим полёта для игрока
    usage: /fly <игрок | *> <enable | disable>
    permission: elytramix.essentials.fly
  gm:
    description: Переключает игровой режим
    usage: /gm <режим> <игрок | *>
    permission: elytramix.essentials.gamemode
    aliases: [gamemode]
  heal:
    description: Исцеляет игрока
    usage: /heal <игрок | *>
    permission: elytramix.essentials.heal
  kickall:
    description: Кикает всех игроков
    usage: /kickall
    permission: elytramix.essentials.kickall
  mobkill:
    description: Убивает всех мобов в заданом радиусе
    usage: /mobkill <радиус>
    permission: elytramix.essentials.mobkill
  night:
    description: Устанавливает ночное время суток
    usage: /night
    permission: elytramix.essentials.time
  powertool:
    description: Делает из предмета волшебную палочку
    usage: /pt <команда>
    permission: elytramix.essentials.powertool
    aliases: [pt]
  rain:
    description: Устанавливает дождливую погоду
    usage: /rain
    permission: elytramix.essentials.weather
  sun:
    description: Устанавливает солнечную погоду
    usage: /sun
    permission: elytramix.essentials.weather
  tpall:
    description: Телепортирует всех игроков к вам
    usage: /tpall
    permission: elytramix.essentials.tpall
  tphere:
    description: Телепортирует игрока к вам
    usage: /s <Игрок>
    permission: elytramix.essentials.tphere
    aliases: [s]
  speed:
    description: Изменяет скорость движения
    usage: /speed <число>
    permission: elytramix.essentials.speed
  spawn:
    description: Телепортирует игрока на спавн
    usage: /spawn
    permission: elytramix.essentials.spawn
  setspawn:
    description: Устанавливает спавн в мире где вы находитесь
    usage: /setspawn
    permission: elytramix.essentials.setspawn
  back:
    description: Возвращает вас в последнюю известную точку
    usage: /back
    permission: elytramix.essentials.back


permissions:

  # Main permissions

  elytramix.menu:
    default: op
    description: Открывать меню сценариев
  elytramix.cmd:
    default: op
    description: Открывать меню быстрых команд
  elytramix.tools:
    default: op
    description: Использовать инструменты с плагина
  elytramix.default:
    default: true
    description: Позволяет использовать стандартные команды
  elytramix.debug:
    default: op
    description: Показывать сообщения отладки

  # Essentials permissions

  elytramix.essentials.*:
    default: op
    description: Даёт доступ ко всем коммандам Essentials
    children:
      elytramix.essentials.broadcast: true
      elytramix.essentials.fly: true
      elytramix.essentials.gamemode: true
      elytramix.essentials.heal: true
      elytramix.essentials.kickall: true
      elytramix.essentials.mobkill: true
      elytramix.essentials.time: true
      elytramix.essentials.powertool: true
      elytramix.essentials.weather: true
      elytramix.essentials.tpall: true
      elytramix.essentials.tphere: true
      elytramix.essentials.speed: true
      elytramix.essentials.spawn: true
      elytramix.essentials.setspawn: true
      elytramix.essentials.back: true

  elytramix.essentials.broadcast:
    default: op
  elytramix.essentials.fly:
    default: op
  elytramix.essentials.gamemode:
    default: op
  elytramix.essentials.heal:
    default: op
  elytramix.essentials.kickall:
    default: op
  elytramix.essentials.mobkill:
    default: op
  elytramix.essentials.time:
    default: op
  elytramix.essentials.powertool:
    default: op
  elytramix.essentials.weather:
    default: op
  elytramix.essentials.tpall:
    default: op
  elytramix.essentials.tphere:
    default: op
  elytramix.essentials.speed:
    default: op
  elytramix.essentials.spawn:
    default: true
  elytramix.essentials.setspawn:
    default: op
  elytramix.essentials.back:
    default: op
